### ISSUE TITLE
Why not add the function of pause ?

### ISSUE THREAD

**Issue by stay4cold** [adrielcafe/AndroidAudioRecorder#1]

**Comment by adrielcafe** [comment]
Would be great!
I'll put on the TODO list and implement ASAP.

**Comment by LiLeiAndroid** [comment]
When the function of pause be added?

**Comment by adrielcafe** [comment]
Currently I'm using [OmRecorder](https://github.com/kailash09dabhi/OmRecorder) lib to record audio. 
At the moment he don't have pause feature. But will be available soon according to [this issue](https://github.com/kailash09dabhi/OmRecorder/issues/1).
I'm waiting to implement in my library.
Thanks for you patience!

**Comment by LiLeiAndroid** [comment]
Looking forward to you implement that feature，Think you！

**Comment by adrielcafe** [comment]
Done!
