### ISSUE TITLE
mp3 file

### ISSUE THREAD

**Issue by milayihe** [adrielcafe/AndroidAudioRecorder#11]
support mp3 file ?

**Comment by adrielcafe** [comment]
Only WAV 😕 

**But** you can use my other lib ([AndroidAudioConverter](https://github.com/adrielcafe/AndroidAudioConverter)) to convert the recorded WAV file to AAC, MP3, M4A, WMA and FLAC. Example of usage [here](https://github.com/adrielcafe/AndroidAudioRecorder/issues/8#issuecomment-247311572).

Hope this help.
