### ISSUE TITLE
stylish wav file content?

### ISSUE THREAD

**Issue by jp1017** [adrielcafe/AndroidAudioRecorder#13]
eg:

The first byte can be the current time,
The second byte can be the location,
Then it can be the Audio content.

**Comment by adrielcafe** [comment]
Hi @jp1017 

I'm using [OmRecorder](https://github.com/kailash09dabhi/c) to record audio. Can't modify the saved file.

You can get the audio duration this way ([source](http://stackoverflow.com/a/32901068)):
```java
MediaMetadataRetriever mmr = new MediaMetadataRetriever();
mmr.setDataSource(context, FILE_URI);
String durationStr = mmr.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION);
int millSecond = Integer.parseInt(durationStr);
```

About the location of the file, is the same you define here:
```java
AndroidAudioRecorder.with(this)
                .setFilePath(AUDIO_FILE_PATH)
                ...
                .record();
```

Hope this help.

**Comment by jp1017** [comment]
https://github.com/kailash09dabhi/OmRecorder is good. 3ks.
