### ISSUE TITLE
Any equivalent in iOS

### ISSUE THREAD

**Issue by MallorcaSoftware** [adrielcafe/AndroidAudioRecorder#29]
Do you know any other equivalent libraries for iOS?

**Comment by jhogervorst** [comment]
[IQAudioRecorderController](https://github.com/hackiftekhar/IQAudioRecorderController) is an iOS library with similar features, though it has a different UI.

**Comment by MallorcaSoftware** [comment]
@jhogervorst perfect, thanks for your help.
