### ISSUE TITLE
Layout error when rotate screen

### ISSUE THREAD

**Issue by donhuvy** [adrielcafe/AndroidAudioRecorder#6]
I am using ASUS Zenfone C
Buttons are overlap.

![screenshot_2016-09-13-11-43-29](https://cloud.githubusercontent.com/assets/1328316/18461832/a3b82278-79a7-11e6-9554-cd3ec7585176.jpg)

![screenshot_2016-09-13-11-44-07](https://cloud.githubusercontent.com/assets/1328316/18461833/a3ba4f30-79a7-11e6-865c-59ed046c8dc5.jpg)

![screenshot_2016-09-13-11-44-12](https://cloud.githubusercontent.com/assets/1328316/18461834/a3ba47a6-79a7-11e6-9d4d-045b7c4e3652.jpg)

**Comment by adrielcafe** [comment]
Hi @donhuvy, thanks for your feedback!

Just release a new version ([0.0.9](https://github.com/adrielcafe/AndroidAudioRecorder/releases/tag/0.0.9)) with fix this. For now only supports **portrait orientation**. 

In the future I'll add support to **landscape orientation**.
