### ISSUE TITLE
[Improvement] I hope this app can save audio file.

### ISSUE THREAD

**Issue by donhuvy** [adrielcafe/AndroidAudioRecorder#7]
I can record, I can play. But the application is no mean, if it can't save to audio file. I hove the app will have save option, or automatic save.

**Comment by adrielcafe** [comment]
Hi @donhuvy!

To save the audio file just click on this `check button` below (after pause the recording):
![device-2016-09-14-102353](https://cloud.githubusercontent.com/assets/2512298/18513918/daae285e-7a65-11e6-8971-6dff7d1ee750.png)

**Note**:  this is just a library to record and save audio, it will not manage the audio files. You can use an [file manager app](https://play.google.com/store/search?q=file%20manager&c=apps) to check if translation was saved.

Some possible issues:
1. Maybe the `WRITE_EXTERNAL_STORAGE` permission is disabled (please [check this](http://www.howtogeek.com/230683/how-to-manage-app-permissions-on-android-6.0/))
2. Device with [insufficient storage available](http://www.pcadvisor.co.uk/how-to/google-android/how-fix-androids-insufficient-storage-available-error-message-summary-cache-3623467/)

Please let me know if this solve your problem.

**Comment by donhuvy** [comment]
Oh, thank you. I don't know about this before your comment. I will try. For better User experience, you should change icon image.

**Comment by adrielcafe** [comment]
Nice! Thanks for you feedback. 

Soon I'll add animations and improve the icons.
