### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ihareshvaghela** [adrielcafe/AndroidAudioRecorder#75]
java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setVisible(boolean)' on a null object reference
        at cafe.adriel.androidaudiorecorder.AudioRecorderActivity.resumeRecording(AudioRecorderActivity.java:268)

**Comment by akardas16** [comment]
> java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setVisible(boolean)' on a null object reference
>         at cafe.adriel.androidaudiorecorder.AudioRecorderActivity.resumeRecording(AudioRecorderActivity.java:268)

Just remove code related to menu items and menu I solved this way

**Comment by EzekielWachira** [comment]
How did you emove code related to menu items and menu @akardas16 . I'm experiencing this issue
